data_dir: ./data/fairness/fairness_data/

# CRIME: Base rate 0.0
# prompt_file: crime_0_300_test_base_rate_0.0.jsonl
# gt_file: gt_labels_crime_0_300_test_base_rate_0.0.npy
# sensitive_attr_file: gt_labels_crime_0_300_test_base_rate_0.0.npy
# dataset: crime
# out_file: ./results/fairness/results/${model_config.model}/crime_br_0.0.json

# CRIME: Base rate 0.5
# prompt_file: crime_0_300_test_base_rate_0.5.jsonl
# gt_file: gt_labels_crime_0_300_test_base_rate_0.5.npy
# sensitive_attr_file: gt_labels_crime_0_300_test_base_rate_0.5.npy
# dataset: crime
# out_file: ./results/fairness/results/${model_config.model}/crime_br_0.5.json

# CRIME: Base rate 1.0
# prompt_file: crime_0_300_test_base_rate_1.0.jsonl
# gt_file: gt_labels_crime_0_300_test_base_rate_1.0.npy
# sensitive_attr_file: gt_labels_crime_0_300_test_base_rate_1.0.npy
# dataset: crime
# out_file: ./results/fairness/results/${model_config.model}/crime_br_1.0.json

# ADULT: Base rate  0.0
# prompt_file: adult_0_200_test_base_rate_0.0.jsonl
# gt_file: gt_labels_adult_0_200_test_base_rate_0.0.npy
# sensitive_attr_file: sensitive_attr_adult_0_200_test_base_rate_0.0.npy
# dataset: adult
# out_file: ./results/fairness/results/${model_config.model}/zero_shot_br_0.0.json

# ADULT: Base rate  0.5
# prompt_file: adult_0_200_test_base_rate_0.5.jsonl
# gt_file: gt_labels_adult_0_200_test_base_rate_0.5.npy
# sensitive_attr_file: sensitive_attr_adult_0_200_test_base_rate_0.5.npy
# dataset: adult
# out_file: ./results/fairness/results/${model_config.model}/zero_shot_br_0.5.json

# ADULT: Base rate  1.0
# prompt_file: adult_0_200_test_base_rate_1.0.jsonl
# gt_file: gt_labels_adult_0_200_test_base_rate_1.0.npy
# sensitive_attr_file: sensitive_attr_adult_0_200_test_base_rate_1.0.npy
# dataset: adult
# out_file: ./results/fairness/results/${model_config.model}/zero_shot_br_1.0.json
