skip_generation: False
n_gens: 25
out_dir: ./results/stereotype/generations/${model_config.model}/${.sys_prompt_type}

# sys_prompt_type: targeted     # ==> Adversarial Attack: TARGETED
# sys_prompt_type: untargeted   # ==> Adversarial Attack: UNTARGETED
