template: 1
max_tokens: 150
n: 25
t: 1
save_interval: 100
api: null

# Non-Toxic Adversarial
# data_file: ./data/toxicity/user_prompts/nontoxic.jsonl
# out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/nontoxic-template-${.template}-generations.jsonl

# Toxic Adversarial
# data_file: ./data/toxicity/user_prompts/toxic.jsonl
# out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/toxic-template-${.template}-generations.jsonl

# Toxic GPT3.5 Adversarial
# data_file: ./data/toxicity/user_prompts/toxic.jsonl.gpt3.n=25.out1.split.annotated.jsonl.filtered.jsonl
# out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/toxic-gpt3.5-template-${.template}-generations.jsonl

# Toxic GPT4 Adversarial
# data_file: ./data/toxicity/user_prompts/toxic.jsonl.gpt4.n=25.out1.split.annotated.jsonl.filtered.jsonl
# out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/toxic-gpt4-template-${.template}-generations.jsonl
